# Generated by Django 4.1 on 2024-03-05 22:40

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
    ]
